package com.banyawa.sitescanner.core.export

import com.banyawa.sitescanner.core.floorplan.Elevation
import com.banyawa.sitescanner.core.floorplan.ElevationOpening
import com.banyawa.sitescanner.core.floorplan.Hinge
import com.banyawa.sitescanner.core.floorplan.OpeningType
import com.banyawa.sitescanner.core.geometry.Vec2
import com.banyawa.sitescanner.core.units.LengthFormat

/**
 * Wall elevations in millimetres, laid out side by side: each wall seen from inside the
 * room with its openings (door swings marked on the hinge side), running dimensions along
 * the floor, heights, AR measurements and the scan of the wall as a tracing underlay (the
 * wall surface and objects standing in front of it on separate layers). Floor level is
 * y = 0 on every elevation.
 */
object ElevationDxf {
    const val LAYER_WALL = "A-ELEV-WALL"
    const val LAYER_DOORS = "A-ELEV-DOOR"
    const val LAYER_WINDOWS = "A-ELEV-GLAZ"
    const val LAYER_TAGS = "A-ELEV-TAG"
    const val LAYER_DIMS = "A-ELEV-DIMS"
    const val LAYER_MEASURE = "A-ELEV-MEAS"
    const val LAYER_SCAN = "A-ELEV-SCAN"
    const val LAYER_SCAN_FRONT = "A-ELEV-SCAN-FRONT"
    const val LAYER_NOTES = "A-ELEV-NOTE"

    data class Options(
        val title: String? = null,
        val textHeightMm: Double = 100.0,
        /** Space between neighbouring elevations. */
        val gapMm: Double = 2500.0,
        val includeScan: Boolean = true,
    )

    /** [tags] are the openings' drawing tags (D1, W1…) by opening id, as on the plan. */
    fun build(elevations: List<Elevation>, tags: Map<String, String>, options: Options = Options()): DxfDocument {
        val dxf = DxfDocument()
            .layer(LAYER_WALL, 7)
            .layer(LAYER_DOORS, 4)
            .layer(LAYER_WINDOWS, 5)
            .layer(LAYER_TAGS, 6)
            .layer(LAYER_DIMS, 2)
            .layer(LAYER_MEASURE, 1)
            .layer(LAYER_SCAN, 8)
            .layer(LAYER_SCAN_FRONT, 30)
            .layer(LAYER_NOTES, 3)
        val th = options.textHeightMm

        var x = 0.0
        for (e in elevations) {
            elevation(dxf, e, x, tags, options)
            x += e.length * 1000.0 + options.gapMm
        }

        val top = (elevations.maxOfOrNull { it.height } ?: 0f) * 1000.0 + th * 8
        val notes = buildList {
            options.title?.takeIf { it.isNotBlank() }?.let { add(it) }
            add("Wall elevations seen from inside the room. Floor = 0, units: millimetres.")
            add("Layers $LAYER_SCAN: scanned wall surface, $LAYER_SCAN_FRONT: objects up to 300 mm in front of the wall.")
            add("Generated by Site Scanner - verify critical dimensions on site.")
        }
        var y = top
        for (line in notes.asReversed()) {
            dxf.text(LAYER_NOTES, 0.0, y, th * 1.2, line)
            y += th * 2
        }
        return dxf
    }

    private fun elevation(dxf: DxfDocument, e: Elevation, ox: Double, tags: Map<String, String>, options: Options) {
        val th = options.textHeightMm
        val thf = th.toFloat()
        val w = e.length * 1000f
        val h = e.height * 1000f
        fun at(xmm: Float, ymm: Float) = Vec2(ox.toFloat() + xmm, ymm)
        fun seg(layer: String, a: Vec2, b: Vec2) = dxf.line(layer, a.x.toDouble(), a.y.toDouble(), b.x.toDouble(), b.y.toDouble())
        fun rect(layer: String, x0: Float, y0: Float, x1: Float, y1: Float) {
            seg(layer, at(x0, y0), at(x1, y0))
            seg(layer, at(x1, y0), at(x1, y1))
            seg(layer, at(x1, y1), at(x0, y1))
            seg(layer, at(x0, y1), at(x0, y0))
        }

        if (options.includeScan) {
            for (i in 0 until e.pointCount) {
                val layer = if (e.points[i * 3 + 2] > Elevation.SURFACE_DEPTH) LAYER_SCAN_FRONT else LAYER_SCAN
                dxf.point(layer, ox + e.points[i * 3] * 1000.0, e.points[i * 3 + 1] * 1000.0)
            }
        }
        rect(LAYER_WALL, 0f, 0f, w, h)

        for (o in e.openings) opening(dxf, o, tags[o.opening.id].orEmpty(), ox, th)

        // Running dimensions along the floor: corner, opening edges, corner; then overall.
        val down = Vec2(0f, -1f)
        val stops = (listOf(0f, w) + e.openings.flatMap { listOf(it.left * 1000f, it.right * 1000f) })
            .map { it.coerceIn(0f, w) }
            .sorted()
            .fold(mutableListOf<Float>()) { acc, v -> if (acc.isEmpty() || v - acc.last() > MIN_DIMENSION) acc += v; acc }
        if (stops.size > 2) {
            for (k in 0 until stops.size - 1) {
                DxfDrafting.dimension(dxf, LAYER_DIMS, at(stops[k], 0f), at(stops[k + 1], 0f), down, thf * 4, thf)
            }
        }
        DxfDrafting.dimension(dxf, LAYER_DIMS, at(0f, 0f), at(w, 0f), down, thf * 8, thf, DxfDrafting.mm(e.length))
        DxfDrafting.dimension(dxf, LAYER_DIMS, at(0f, 0f), at(0f, h), Vec2(-1f, 0f), thf * 4, thf, DxfDrafting.mm(e.height))

        for (m in e.measurements) {
            val a = at(m.x0 * 1000f, m.z0 * 1000f)
            val b = at(m.x1 * 1000f, m.z1 * 1000f)
            seg(LAYER_MEASURE, a, b)
            val label = listOf(m.label, LengthFormat.toMillimeters(m.lengthM).toString()).filter { it.isNotEmpty() }.joinToString(" = ")
            val dir = (b - a).normalized()
            val mid = Vec2.lerp(a, b, 0.5f) + dir.perp() * (thf * 0.4f)
            dxf.text(LAYER_MEASURE, mid.x.toDouble(), mid.y.toDouble(), th * 0.8, label, DxfDrafting.readableAngle(dir), DxfDocument.HAlign.CENTER)
        }

        val titleY = -th * 14
        dxf.text(LAYER_NOTES, ox, titleY, th * 1.8, "ELEVATION ${e.key}")
        dxf.text(
            LAYER_NOTES, ox, titleY - th * 2.4, th * 0.9,
            "Wall ${DxfDrafting.mm(e.length)} mm, floor to ceiling ${DxfDrafting.mm(e.height)} mm, seen from inside the room",
        )
    }

    /**
     * Opening outline with its tag and size in the middle and its heights dimensioned beside
     * the right jamb. A door with a known swing gets the elevation convention: lines from the
     * corners of the free edge meeting at the hinge side.
     */
    private fun opening(dxf: DxfDocument, o: ElevationOpening, tag: String, ox: Double, th: Double) {
        val thf = th.toFloat()
        val window = o.opening.type == OpeningType.WINDOW
        val layer = if (window) LAYER_WINDOWS else LAYER_DOORS
        val x0 = ox.toFloat() + o.left * 1000f
        val x1 = ox.toFloat() + o.right * 1000f
        val y0 = o.bottom * 1000f
        val y1 = o.top * 1000f
        fun seg(a: Vec2, b: Vec2) = dxf.line(layer, a.x.toDouble(), a.y.toDouble(), b.x.toDouble(), b.y.toDouble())
        seg(Vec2(x0, y0), Vec2(x1, y0))
        seg(Vec2(x1, y0), Vec2(x1, y1))
        seg(Vec2(x1, y1), Vec2(x0, y1))
        seg(Vec2(x0, y1), Vec2(x0, y0))

        fun leaf(hingeX: Float, freeX: Float) {
            val apex = Vec2(hingeX, (y0 + y1) / 2f)
            seg(Vec2(freeX, y0), apex)
            seg(Vec2(freeX, y1), apex)
        }
        when (o.swing?.hinge) {
            Hinge.LEFT -> leaf(x0, x1)
            Hinge.RIGHT -> leaf(x1, x0)
            Hinge.BOTH -> {
                leaf(x0, (x0 + x1) / 2f)
                leaf(x1, (x0 + x1) / 2f)
            }
            null -> Unit
        }

        val cx = ((x0 + x1) / 2f).toDouble()
        val cy = ((y0 + y1) / 2f).toDouble()
        dxf.text(LAYER_TAGS, cx, cy + th * 0.4, th * 1.4, tag, align = DxfDocument.HAlign.CENTER)
        val size = "${DxfDrafting.mm(o.width)}x${DxfDrafting.mm(o.opening.height)}" + (o.swing?.let { " ${it.code}" } ?: "")
        dxf.text(LAYER_TAGS, cx, cy - th * 1.2, th * 0.8, size, align = DxfDocument.HAlign.CENTER)

        val right = Vec2(1f, 0f)
        if (window) {
            DxfDrafting.dimension(dxf, LAYER_DIMS, Vec2(x1, 0f), Vec2(x1, y0), right, thf * 2, thf, DxfDrafting.mm(o.bottom))
        }
        DxfDrafting.dimension(dxf, LAYER_DIMS, Vec2(x1, y0), Vec2(x1, y1), right, thf * 2, thf, DxfDrafting.mm(o.top - o.bottom))
    }

    /** Stops closer than this (mm) are not dimensioned separately. */
    private const val MIN_DIMENSION = 20f
}
