package com.banyawa.sitescanner.core.export

import com.banyawa.sitescanner.core.floorplan.FloorPlan
import com.banyawa.sitescanner.core.geometry.Vec2
import com.banyawa.sitescanner.core.project.Measurement
import com.banyawa.sitescanner.core.units.LengthFormat
import kotlin.math.atan2

/**
 * Builds a 2D plan drawing in millimetres: walls, aligned dimension strings, AR
 * measurements (as 3D lines) and, optionally, the raw scan slice as a tracing underlay.
 */
object FloorPlanDxf {
    const val LAYER_WALLS = "A-WALL"
    const val LAYER_DIMS = "A-DIMS"
    const val LAYER_MEASURE = "A-MEAS"
    const val LAYER_SLICE = "A-SCAN-SLICE"
    const val LAYER_NOTES = "A-NOTE"

    data class Options(
        val title: String? = null,
        val dimensionOffsetMm: Double = 400.0,
        val textHeightMm: Double = 100.0,
        val includeSlice: Boolean = true,
        val maxSlicePoints: Int = 60_000,
    )

    fun build(
        plan: FloorPlan,
        slice: FloatArray? = null,
        measurements: List<Measurement> = emptyList(),
        options: Options = Options(),
    ): DxfDocument {
        val dxf = DxfDocument()
            .layer(LAYER_WALLS, 7)
            .layer(LAYER_DIMS, 2)
            .layer(LAYER_MEASURE, 1)
            .layer(LAYER_SLICE, 8)
            .layer(LAYER_NOTES, 3)
        val th = options.textHeightMm

        if (options.includeSlice && slice != null && slice.isNotEmpty()) {
            val n = slice.size / 2
            val step = maxOf(1, (n + options.maxSlicePoints - 1) / options.maxSlicePoints)
            var i = 0
            while (i < n) {
                dxf.point(LAYER_SLICE, slice[i * 2] * 1000.0, slice[i * 2 + 1] * 1000.0)
                i += step
            }
        }

        val centroid = plan.walls.map { it.midpoint }.let { mids ->
            if (mids.isEmpty()) Vec2.ZERO else mids.reduce { a, b -> a + b } * (1f / mids.size)
        }
        for (w in plan.walls) {
            dxf.line(LAYER_WALLS, w.start.x * 1000.0, w.start.y * 1000.0, w.end.x * 1000.0, w.end.y * 1000.0)
            dimension(dxf, w.start, w.end, centroid, options)
        }

        for (m in measurements) {
            val a = plan.alignment.toSite(m.start)
            val b = plan.alignment.toSite(m.end)
            dxf.line(
                LAYER_MEASURE,
                a.x * 1000.0, a.y * 1000.0, a.z * 1000.0,
                b.x * 1000.0, b.y * 1000.0, b.z * 1000.0,
            )
            val label = listOf(m.label.trim(), "${LengthFormat.toMillimeters(m.lengthM)}").filter { it.isNotEmpty() }.joinToString(" = ")
            dxf.text(
                LAYER_MEASURE,
                (a.x + b.x) * 500.0,
                (a.y + b.y) * 500.0 + th * 0.5,
                th,
                label,
                align = DxfDocument.HAlign.CENTER,
            )
        }

        val bounds = plan.bounds()
        val noteX = (bounds?.min?.x ?: 0f) * 1000.0
        var noteY = (bounds?.max?.y ?: 0f) * 1000.0 + options.dimensionOffsetMm + th * 6
        val notes = buildList {
            options.title?.takeIf { it.isNotBlank() }?.let { add(it) }
            plan.roomHeight?.let { add("Floor to ceiling: ${LengthFormat.toMillimeters(it)} mm") }
            add("Walls: ${plan.walls.size}, total length ${LengthFormat.toMillimeters(plan.totalWallLength)} mm")
            add("Units: millimetres. Generated by Site Scanner - verify critical dimensions on site.")
        }
        for (line in notes.asReversed()) {
            dxf.text(LAYER_NOTES, noteX, noteY, th * 1.2, line)
            noteY += th * 2
        }
        return dxf
    }

    private fun dimension(dxf: DxfDocument, startM: Vec2, endM: Vec2, centroid: Vec2, options: Options) {
        val lengthM = startM.distanceTo(endM)
        if (lengthM <= 0f) return
        val dir = (endM - startM).normalized()
        var normal = dir.perp()
        if ((Vec2.lerp(startM, endM, 0.5f) - centroid) dot normal < 0f) normal = -normal

        val s = startM * 1000f
        val e = endM * 1000f
        val off = options.dimensionOffsetMm.toFloat()
        val th = options.textHeightMm.toFloat()
        val ds = s + normal * off
        val de = e + normal * off

        // Extension lines: small gap at the wall, overshoot past the dimension line.
        val gap = 50f
        val over = 80f
        line(dxf, s + normal * gap, s + normal * (off + over))
        line(dxf, e + normal * gap, e + normal * (off + over))
        line(dxf, ds, de)
        // Architectural 45° ticks.
        val tick = (dir + normal).normalized() * (th * 0.6f)
        line(dxf, ds - tick, ds + tick)
        line(dxf, de - tick, de + tick)

        var angle = Math.toDegrees(atan2(dir.y.toDouble(), dir.x.toDouble()))
        if (angle > 90.0) angle -= 180.0
        if (angle <= -90.0) angle += 180.0
        val mid = Vec2.lerp(ds, de, 0.5f) + normal * (th * 0.4f)
        dxf.text(
            LAYER_DIMS,
            mid.x.toDouble(),
            mid.y.toDouble(),
            th.toDouble(),
            LengthFormat.toMillimeters(lengthM).toString(),
            rotationDeg = angle,
            align = DxfDocument.HAlign.CENTER,
        )
    }

    private fun line(dxf: DxfDocument, a: Vec2, b: Vec2) =
        dxf.line(LAYER_DIMS, a.x.toDouble(), a.y.toDouble(), b.x.toDouble(), b.y.toDouble())
}
