package com.banyawa.sitescanner.core.export

import com.banyawa.sitescanner.core.floorplan.DoorLeaf
import com.banyawa.sitescanner.core.floorplan.FloorPlan
import com.banyawa.sitescanner.core.floorplan.Opening
import com.banyawa.sitescanner.core.floorplan.OpeningTags
import com.banyawa.sitescanner.core.floorplan.OpeningType
import com.banyawa.sitescanner.core.geometry.Vec2
import com.banyawa.sitescanner.core.project.Measurement
import com.banyawa.sitescanner.core.units.LengthFormat
import kotlin.math.atan2

/**
 * Builds a 2D plan drawing in millimetres: walls, aligned dimension strings, door and
 * window symbols with tags and a schedule, AR measurements (as 3D lines) and, optionally,
 * the raw scan slice as a tracing underlay.
 */
object FloorPlanDxf {
    const val LAYER_WALLS = "A-WALL"
    const val LAYER_DIMS = "A-DIMS"
    const val LAYER_MEASURE = "A-MEAS"
    const val LAYER_SLICE = "A-SCAN-SLICE"
    const val LAYER_NOTES = "A-NOTE"
    const val LAYER_DOORS = "A-DOOR"
    const val LAYER_WINDOWS = "A-GLAZ"
    const val LAYER_TAGS = "A-OPEN-TAG"
    const val LAYER_SCHEDULE = "A-SCHED"

    data class Options(
        val title: String? = null,
        val dimensionOffsetMm: Double = 400.0,
        val textHeightMm: Double = 100.0,
        val includeSlice: Boolean = true,
        val maxSlicePoints: Int = 60_000,
    )

    fun build(
        plan: FloorPlan,
        slice: FloatArray? = null,
        measurements: List<Measurement> = emptyList(),
        options: Options = Options(),
    ): DxfDocument {
        val dxf = DxfDocument()
            .layer(LAYER_WALLS, 7)
            .layer(LAYER_DIMS, 2)
            .layer(LAYER_MEASURE, 1)
            .layer(LAYER_SLICE, 8)
            .layer(LAYER_NOTES, 3)
            .layer(LAYER_DOORS, 4)
            .layer(LAYER_WINDOWS, 5)
            .layer(LAYER_TAGS, 6)
            .layer(LAYER_SCHEDULE, 3)
        val th = options.textHeightMm

        if (options.includeSlice && slice != null && slice.isNotEmpty()) {
            val n = slice.size / 2
            val step = maxOf(1, (n + options.maxSlicePoints - 1) / options.maxSlicePoints)
            var i = 0
            while (i < n) {
                dxf.point(LAYER_SLICE, slice[i * 2] * 1000.0, slice[i * 2 + 1] * 1000.0)
                i += step
            }
        }

        val centroid = plan.walls.map { it.midpoint }.let { mids ->
            if (mids.isEmpty()) Vec2.ZERO else mids.reduce { a, b -> a + b } * (1f / mids.size)
        }
        for (w in plan.walls) {
            dxf.line(LAYER_WALLS, w.start.x * 1000.0, w.start.y * 1000.0, w.end.x * 1000.0, w.end.y * 1000.0)
            dimension(dxf, w.start, w.end, centroid, options)
        }

        val tags = OpeningTags.assign(plan.openings)
        for (o in plan.openings) opening(dxf, o, tags.getValue(o.id), th)

        for (m in measurements) {
            val a = plan.alignment.toSite(m.start)
            val b = plan.alignment.toSite(m.end)
            dxf.line(
                LAYER_MEASURE,
                a.x * 1000.0, a.y * 1000.0, a.z * 1000.0,
                b.x * 1000.0, b.y * 1000.0, b.z * 1000.0,
            )
            val label = listOf(m.label.trim(), "${LengthFormat.toMillimeters(m.lengthM)}").filter { it.isNotEmpty() }.joinToString(" = ")
            dxf.text(
                LAYER_MEASURE,
                (a.x + b.x) * 500.0,
                (a.y + b.y) * 500.0 + th * 0.5,
                th,
                label,
                align = DxfDocument.HAlign.CENTER,
            )
        }

        val bounds = plan.bounds()
        val noteX = (bounds?.min?.x ?: 0f) * 1000.0
        var noteY = (bounds?.max?.y ?: 0f) * 1000.0 + options.dimensionOffsetMm + th * 6
        val notes = buildList {
            options.title?.takeIf { it.isNotBlank() }?.let { add(it) }
            plan.roomHeight?.let { add("Floor to ceiling: ${LengthFormat.toMillimeters(it)} mm") }
            add("Walls: ${plan.walls.size}, total length ${LengthFormat.toMillimeters(plan.totalWallLength)} mm")
            if (plan.openings.isNotEmpty()) {
                val doors = plan.openings.count { it.type != OpeningType.WINDOW }
                val windows = plan.openings.count { it.type == OpeningType.WINDOW }
                add("Doors / openings: $doors, windows: $windows (clear sizes; verify rough openings on site)")
            }
            add("Units: millimetres. Generated by Site Scanner - verify critical dimensions on site.")
        }
        for (line in notes.asReversed()) {
            dxf.text(LAYER_NOTES, noteX, noteY, th * 1.2, line)
            noteY += th * 2
        }

        if (plan.openings.isNotEmpty()) {
            val top = (bounds?.min?.y ?: 0f) * 1000.0 - options.dimensionOffsetMm - th * 6
            schedule(dxf, plan.openings, tags, noteX, top, th)
        }
        return dxf
    }

    /**
     * Door: jamb ticks plus the leaf drawn open at 90° with its swing arc, or a threshold
     * line when the swing is unknown. Window: glazing box straddling the wall. Both get a tag.
     */
    private fun opening(dxf: DxfDocument, o: Opening, tag: String, th: Double) {
        val s = o.start * 1000f
        val e = o.end * 1000f
        val n = o.interiorNormal
        fun seg(layer: String, a: Vec2, b: Vec2) = dxf.line(layer, a.x.toDouble(), a.y.toDouble(), b.x.toDouble(), b.y.toDouble())

        val size = "${mm(o.width)}x${mm(o.height)}"
        val detail = if (o.type == OpeningType.WINDOW) {
            val jamb = n * 50f
            seg(LAYER_WINDOWS, s - jamb, e - jamb)
            seg(LAYER_WINDOWS, s + jamb, e + jamb)
            seg(LAYER_WINDOWS, s - jamb, s + jamb)
            seg(LAYER_WINDOWS, e - jamb, e + jamb)
            seg(LAYER_WINDOWS, s, e)
            "$size SILL ${mm(o.bottom)}"
        } else {
            val jamb = n * 75f
            seg(LAYER_DOORS, s - jamb, s + jamb)
            seg(LAYER_DOORS, e - jamb, e + jamb)
            val leaves = o.leaves
            if (leaves.isEmpty()) seg(LAYER_DOORS, s, e)
            for (leaf in leaves) swing(dxf, leaf)
            size
        }
        // Labels run along the wall, on the room side.
        val angle = readableAngle(o.direction)
        val mid = Vec2.lerp(s, e, 0.5f)
        val tagAt = mid + n * (th * 3.5).toFloat()
        dxf.text(LAYER_TAGS, tagAt.x.toDouble(), tagAt.y.toDouble(), th * 1.4, tag, angle, DxfDocument.HAlign.CENTER)
        val detailAt = mid + n * (th * 1.6).toFloat()
        dxf.text(LAYER_TAGS, detailAt.x.toDouble(), detailAt.y.toDouble(), th * 0.8, detail, angle, DxfDocument.HAlign.CENTER)
    }

    private fun swing(dxf: DxfDocument, leaf: DoorLeaf) {
        val h = leaf.hinge * 1000f
        val open = leaf.open * 1000f
        val closed = leaf.closed * 1000f
        dxf.line(LAYER_DOORS, h.x.toDouble(), h.y.toDouble(), open.x.toDouble(), open.y.toDouble())
        val toOpen = open - h
        val toClosed = closed - h
        val aOpen = Math.toDegrees(atan2(toOpen.y.toDouble(), toOpen.x.toDouble()))
        val aClosed = Math.toDegrees(atan2(toClosed.y.toDouble(), toClosed.x.toDouble()))
        // DXF arcs run counter-clockwise; the quarter turn goes whichever way the leaf swings.
        val (from, to) = if ((toClosed cross toOpen) > 0f) aClosed to aOpen else aOpen to aClosed
        dxf.arc(LAYER_DOORS, h.x.toDouble(), h.y.toDouble(), h.distanceTo(closed).toDouble(), normalizeDeg(from), normalizeDeg(to))
    }

    private fun normalizeDeg(deg: Double) = ((deg % 360.0) + 360.0) % 360.0

    /** Text angle along [dir], flipped so it never reads upside down. */
    private fun readableAngle(dir: Vec2): Double {
        var angle = Math.toDegrees(atan2(dir.y.toDouble(), dir.x.toDouble()))
        if (angle > 90.0) angle -= 180.0
        if (angle <= -90.0) angle += 180.0
        return angle
    }

    /** Door / window schedule as a text table (one TEXT per cell so columns line up). */
    private fun schedule(dxf: DxfDocument, openings: List<Opening>, tags: Map<String, String>, x: Double, top: Double, th: Double) {
        val columns = doubleArrayOf(0.0, 800.0, 2000.0, 3000.0, 4000.0, 5000.0, 6000.0, 7400.0, 8600.0)
        val header = listOf("TAG", "TYPE", "WIDTH", "HEIGHT", "SILL", "HEAD", "FROM LEFT", "SWING", "CHECK")
        dxf.text(LAYER_SCHEDULE, x, top, th * 1.4, "DOOR / WINDOW SCHEDULE (mm, clear opening from scan)")
        dxf.text(
            LAYER_SCHEDULE, x, top - th * 2, th * 0.8,
            "FROM LEFT / SWING: seen from inside the room facing the wall. L / R / PAIR = hinge side, IN = opens into the room.",
        )
        var y = top - th * 4.5
        header.forEachIndexed { i, h -> dxf.text(LAYER_SCHEDULE, x + columns[i], y, th, h) }
        y -= th * 0.6
        dxf.line(LAYER_SCHEDULE, x, y, x + columns.last() + 800.0, y)
        val ordered = openings.sortedWith(compareBy({ it.type.ordinal }, { tags[it.id]?.drop(1)?.toIntOrNull() ?: 0 }))
        for (o in ordered) {
            y -= th * 1.8
            val row = listOf(
                tags.getValue(o.id),
                o.type.name,
                mm(o.width),
                mm(o.height),
                if (o.type == OpeningType.WINDOW) mm(o.bottom) else "-",
                mm(o.top),
                mm(o.distanceFromWallStart),
                o.swing?.code ?: "",
                when {
                    o.manual -> "MANUAL"
                    o.needsCheck -> "VERIFY"
                    else -> ""
                },
            )
            row.forEachIndexed { i, v -> if (v.isNotEmpty()) dxf.text(LAYER_SCHEDULE, x + columns[i], y, th, v) }
        }
    }

    private fun mm(m: Float) = LengthFormat.toMillimeters(m).toString()

    private fun dimension(dxf: DxfDocument, startM: Vec2, endM: Vec2, centroid: Vec2, options: Options) {
        val lengthM = startM.distanceTo(endM)
        if (lengthM <= 0f) return
        val dir = (endM - startM).normalized()
        var normal = dir.perp()
        if ((Vec2.lerp(startM, endM, 0.5f) - centroid) dot normal < 0f) normal = -normal

        val s = startM * 1000f
        val e = endM * 1000f
        val off = options.dimensionOffsetMm.toFloat()
        val th = options.textHeightMm.toFloat()
        val ds = s + normal * off
        val de = e + normal * off

        // Extension lines: small gap at the wall, overshoot past the dimension line.
        val gap = 50f
        val over = 80f
        line(dxf, s + normal * gap, s + normal * (off + over))
        line(dxf, e + normal * gap, e + normal * (off + over))
        line(dxf, ds, de)
        // Architectural 45° ticks.
        val tick = (dir + normal).normalized() * (th * 0.6f)
        line(dxf, ds - tick, ds + tick)
        line(dxf, de - tick, de + tick)

        val angle = readableAngle(dir)
        val mid = Vec2.lerp(ds, de, 0.5f) + normal * (th * 0.4f)
        dxf.text(
            LAYER_DIMS,
            mid.x.toDouble(),
            mid.y.toDouble(),
            th.toDouble(),
            LengthFormat.toMillimeters(lengthM).toString(),
            rotationDeg = angle,
            align = DxfDocument.HAlign.CENTER,
        )
    }

    private fun line(dxf: DxfDocument, a: Vec2, b: Vec2) =
        dxf.line(LAYER_DIMS, a.x.toDouble(), a.y.toDouble(), b.x.toDouble(), b.y.toDouble())
}
